<?php

use \Drupal\payone_payment\CreditCardController;

/**
 * Implements hook_payment_method_controller_info().
 */
function payone_payment_payment_method_controller_info() {
  $controllers['payone_payment_credit_card'] = '\Drupal\payone_payment\CreditCardController';
  return $controllers;
}

/**
 * Implements hook_entity_load().
 */
function payone_payment_entity_load(array $entities, $entity_type) {
  if ($entity_type == 'payment_method') {
    CreditCardController::load($entities);
  }
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function payone_payment_payment_method_insert(PaymentMethod $method) {
  if ($method->controller instanceof CreditCardController)
    $method->controller->insert($method);
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function payone_payment_payment_method_update(PaymentMethod $method) {
  if ($method->controller instanceof CreditCardController)
    $method->controller->update($method);
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function payone_payment_payment_method_delete($method) {
  if ($method->controller instanceof CreditCardController)
    $method->controller->delete($method);
}

/**
 * Form element callback: Payment method configuration.
 */
function payone_payment_configuration_form($element, &$form_state) {
  $controller = $form_state['payment_method']->controller;
  return $controller->configurationForm($element, $form_state);
}

function payone_payment_configuration_form_validate($element, &$form_state, $form) {
  $controller = $form_state['payment_method']->controller;
  $controller->configurationFormValidate($element, $form_state, $form);
}
